kind: pipeline
type: docker
name: build-push-and-deploy

trigger:
  ref:
    - refs/heads/main
  event:
    - push
    - custom

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      repo: ghaith00/portfolio
      dockerfile: Dockerfile.prod
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

  - name: deploy
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: portfolio_dir
        path: /home/ubuntu/portfolio
    working_dir: /home/ubuntu/portfolio
    environment:
      IMAGE_TAG: latest
      COMPOSE_PROJECT_NAME: portfolio
    commands:
      - docker compose pull || true
      - docker compose up -d
      - docker image prune -f || true

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: portfolio_dir
    host:
      path: /home/ubuntu/portfolio
